services:
  ems-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        - VITE_APP_BACKEND_ADDRESS=http://localhost:5000
    container_name: ems-frontend-prod
    ports:
      - "8000:8000"
    env_file: ".env"
